use crate::types::{BaseType, Type};

pub(super) fn builtin_values() -> Vec<(&'static str, Type)> {
    vec![
        // OHLCV data
        ("open", Type::series(BaseType::Float)),
        ("high", Type::series(BaseType::Float)),
        ("low", Type::series(BaseType::Float)),
        ("close", Type::series(BaseType::Float)),
        ("volume", Type::series(BaseType::Float)),
        // Derived price data
        ("hl2", Type::series(BaseType::Float)),
        ("hlc3", Type::series(BaseType::Float)),
        ("hlcc4", Type::series(BaseType::Float)),
        ("ohlc4", Type::series(BaseType::Float)),
        // Time variables
        ("time", Type::series(BaseType::Int)),
        ("time_close", Type::series(BaseType::Int)),
        ("time_tradingday", Type::series(BaseType::Int)),
        ("timenow", Type::series(BaseType::Int)),
        ("bar_index", Type::series(BaseType::Int)),
        ("last_bar_index", Type::series(BaseType::Int)),
        ("last_bar_time", Type::series(BaseType::Int)),
        // Date/time components
        ("year", Type::series(BaseType::Int)),
        ("month", Type::series(BaseType::Int)),
        ("weekofyear", Type::series(BaseType::Int)),
        ("dayofmonth", Type::series(BaseType::Int)),
        ("dayofweek", Type::series(BaseType::Int)),
        ("hour", Type::series(BaseType::Int)),
        ("minute", Type::series(BaseType::Int)),
        ("second", Type::series(BaseType::Int)),
        // Bid/Ask
        ("ask", Type::series(BaseType::Float)),
        ("bid", Type::series(BaseType::Float)),
        // Special values
        ("na", Type::unknown()),
        ("true", Type::scalar(BaseType::Bool)),
        ("false", Type::scalar(BaseType::Bool)),
        // barstate.* namespace
        ("barstate", Type::unknown()),
        ("barstate.isconfirmed", Type::series(BaseType::Bool)),
        ("barstate.isfirst", Type::series(BaseType::Bool)),
        ("barstate.ishistory", Type::series(BaseType::Bool)),
        ("barstate.islast", Type::series(BaseType::Bool)),
        (
            "barstate.islastconfirmedhistory",
            Type::series(BaseType::Bool),
        ),
        ("barstate.isnew", Type::series(BaseType::Bool)),
        ("barstate.isrealtime", Type::series(BaseType::Bool)),
        // timeframe.* namespace
        ("timeframe", Type::unknown()),
        ("timeframe.isdaily", Type::scalar(BaseType::Bool)),
        ("timeframe.isdwm", Type::scalar(BaseType::Bool)),
        ("timeframe.isintraday", Type::scalar(BaseType::Bool)),
        ("timeframe.isminutes", Type::scalar(BaseType::Bool)),
        ("timeframe.ismonthly", Type::scalar(BaseType::Bool)),
        ("timeframe.isseconds", Type::scalar(BaseType::Bool)),
        ("timeframe.isticks", Type::scalar(BaseType::Bool)),
        ("timeframe.isweekly", Type::scalar(BaseType::Bool)),
        ("timeframe.main_period", Type::scalar(BaseType::Int)),
        ("timeframe.multiplier", Type::scalar(BaseType::Int)),
        ("timeframe.period", Type::scalar(BaseType::String)),
        // session.* namespace
        ("session", Type::unknown()),
        ("session.isfirstbar", Type::series(BaseType::Bool)),
        ("session.isfirstbar_regular", Type::series(BaseType::Bool)),
        ("session.islastbar", Type::series(BaseType::Bool)),
        ("session.islastbar_regular", Type::series(BaseType::Bool)),
        ("session.ismarket", Type::series(BaseType::Bool)),
        ("session.ispostmarket", Type::series(BaseType::Bool)),
        ("session.ispremarket", Type::series(BaseType::Bool)),
        ("session.extended", Type::scalar(BaseType::String)),
        ("session.regular", Type::scalar(BaseType::String)),
        // syminfo.* namespace
        ("syminfo", Type::unknown()),
        ("syminfo.basecurrency", Type::scalar(BaseType::String)),
        ("syminfo.currency", Type::scalar(BaseType::String)),
        ("syminfo.description", Type::scalar(BaseType::String)),
        ("syminfo.mintick", Type::scalar(BaseType::Float)),
        ("syminfo.pointvalue", Type::scalar(BaseType::Float)),
        ("syminfo.pricescale", Type::scalar(BaseType::Int)),
        ("syminfo.root", Type::scalar(BaseType::String)),
        ("syminfo.session", Type::scalar(BaseType::String)),
        ("syminfo.ticker", Type::scalar(BaseType::String)),
        ("syminfo.tickerid", Type::scalar(BaseType::String)),
        ("syminfo.timezone", Type::scalar(BaseType::String)),
        ("syminfo.type", Type::scalar(BaseType::String)),
        ("syminfo.volumetype", Type::scalar(BaseType::String)),
        ("syminfo.country", Type::scalar(BaseType::String)),
        ("syminfo.industry", Type::scalar(BaseType::String)),
        ("syminfo.sector", Type::scalar(BaseType::String)),
        ("syminfo.employees", Type::scalar(BaseType::Int)),
        ("syminfo.shareholders", Type::scalar(BaseType::Int)),
        (
            "syminfo.shares_outstanding_float",
            Type::scalar(BaseType::Float),
        ),
        (
            "syminfo.shares_outstanding_total",
            Type::scalar(BaseType::Float),
        ),
        (
            "syminfo.target_price_average",
            Type::scalar(BaseType::Float),
        ),
        ("syminfo.target_price_high", Type::scalar(BaseType::Float)),
        ("syminfo.target_price_low", Type::scalar(BaseType::Float)),
        ("syminfo.target_price_median", Type::scalar(BaseType::Float)),
        ("syminfo.mincontract", Type::scalar(BaseType::Float)),
        ("syminfo.minmove", Type::scalar(BaseType::Int)),
        ("syminfo.prefix", Type::scalar(BaseType::String)),
        ("syminfo.main_tickerid", Type::scalar(BaseType::String)),
        ("syminfo.expiration_date", Type::scalar(BaseType::Int)),
        ("syminfo.current_contract", Type::scalar(BaseType::String)),
        ("syminfo.isin", Type::scalar(BaseType::String)),
        ("syminfo.recommendations_buy", Type::series(BaseType::Int)),
        (
            "syminfo.recommendations_buy_strong",
            Type::series(BaseType::Int),
        ),
        ("syminfo.recommendations_date", Type::series(BaseType::Int)),
        ("syminfo.recommendations_hold", Type::series(BaseType::Int)),
        ("syminfo.recommendations_sell", Type::series(BaseType::Int)),
        (
            "syminfo.recommendations_sell_strong",
            Type::series(BaseType::Int),
        ),
        (
            "syminfo.recommendations_total",
            Type::series(BaseType::Float),
        ),
        // chart.* namespace
        ("chart", Type::unknown()),
        ("chart.bg_color", Type::series(BaseType::Color)),
        ("chart.fg_color", Type::series(BaseType::Color)),
        ("chart.is_heikinashi", Type::scalar(BaseType::Bool)),
        ("chart.is_kagi", Type::scalar(BaseType::Bool)),
        ("chart.is_linebreak", Type::scalar(BaseType::Bool)),
        ("chart.is_pnf", Type::scalar(BaseType::Bool)),
        ("chart.is_range", Type::scalar(BaseType::Bool)),
        ("chart.is_renko", Type::scalar(BaseType::Bool)),
        ("chart.is_standard", Type::scalar(BaseType::Bool)),
        ("chart.left_visible_bar_time", Type::series(BaseType::Int)),
        ("chart.right_visible_bar_time", Type::series(BaseType::Int)),
        // strategy.* namespace variables
        ("strategy", Type::unknown()),
        ("strategy.equity", Type::series(BaseType::Float)),
        ("strategy.initial_capital", Type::scalar(BaseType::Float)),
        ("strategy.avg_losing_trade", Type::series(BaseType::Float)),
        (
            "strategy.avg_losing_trade_percent",
            Type::series(BaseType::Float),
        ),
        ("strategy.avg_trade", Type::series(BaseType::Float)),
        ("strategy.avg_trade_percent", Type::series(BaseType::Float)),
        ("strategy.avg_winning_trade", Type::series(BaseType::Float)),
        (
            "strategy.avg_winning_trade_percent",
            Type::series(BaseType::Float),
        ),
        ("strategy.netprofit", Type::series(BaseType::Float)),
        ("strategy.netprofit_percent", Type::series(BaseType::Float)),
        ("strategy.grossprofit", Type::series(BaseType::Float)),
        (
            "strategy.grossprofit_percent",
            Type::series(BaseType::Float),
        ),
        ("strategy.grossloss", Type::series(BaseType::Float)),
        ("strategy.grossloss_percent", Type::series(BaseType::Float)),
        ("strategy.openprofit", Type::series(BaseType::Float)),
        ("strategy.openprofit_percent", Type::series(BaseType::Float)),
        ("strategy.position_size", Type::series(BaseType::Float)),
        ("strategy.position_avg_price", Type::series(BaseType::Float)),
        (
            "strategy.position_entry_name",
            Type::series(BaseType::String),
        ),
        (
            "strategy.margin_liquidation_price",
            Type::series(BaseType::Float),
        ),
        (
            "strategy.max_contracts_held_all",
            Type::series(BaseType::Float),
        ),
        (
            "strategy.max_contracts_held_long",
            Type::series(BaseType::Float),
        ),
        (
            "strategy.max_contracts_held_short",
            Type::series(BaseType::Float),
        ),
        ("strategy.closedtrades", Type::series(BaseType::Int)),
        (
            "strategy.closedtrades.first_index",
            Type::series(BaseType::Int),
        ),
        ("strategy.opentrades", Type::series(BaseType::Int)),
        (
            "strategy.opentrades.capital_held",
            Type::series(BaseType::Float),
        ),
        ("strategy.wintrades", Type::series(BaseType::Int)),
        ("strategy.losstrades", Type::series(BaseType::Int)),
        ("strategy.eventrades", Type::series(BaseType::Int)),
        ("strategy.max_drawdown", Type::series(BaseType::Float)),
        (
            "strategy.max_drawdown_percent",
            Type::series(BaseType::Float),
        ),
        ("strategy.max_runup", Type::series(BaseType::Float)),
        ("strategy.max_runup_percent", Type::series(BaseType::Float)),
        ("strategy.account_currency", Type::scalar(BaseType::String)),
        // ta.* built-in variables (not functions)
        ("ta", Type::unknown()),
        ("ta.accdist", Type::series(BaseType::Float)),
        ("ta.iii", Type::series(BaseType::Float)),
        ("ta.nvi", Type::series(BaseType::Float)),
        ("ta.pvi", Type::series(BaseType::Float)),
        ("ta.pvt", Type::series(BaseType::Float)),
        ("ta.wad", Type::series(BaseType::Float)),
        ("ta.wvad", Type::series(BaseType::Float)),
        // Other namespaces
        ("math", Type::unknown()),
        ("input", Type::unknown()),
        ("request", Type::unknown()),
        ("color", Type::unknown()),
        ("array", Type::unknown()),
        ("matrix", Type::unknown()),
        ("map", Type::unknown()),
        ("str", Type::unknown()),
        ("label", Type::unknown()),
        ("line", Type::unknown()),
        ("box", Type::unknown()),
        ("table", Type::unknown()),
        ("polyline", Type::unknown()),
        // Drawing object collections
        ("label.all", Type::unknown()),
        ("line.all", Type::unknown()),
        ("box.all", Type::unknown()),
        ("table.all", Type::unknown()),
        ("linefill.all", Type::unknown()),
        ("polyline.all", Type::unknown()),
        // dividends.* namespace
        ("dividends", Type::unknown()),
        ("dividends.gross", Type::scalar(BaseType::String)),
        ("dividends.net", Type::scalar(BaseType::String)),
        ("dividends.future_amount", Type::series(BaseType::Float)),
        ("dividends.future_ex_date", Type::series(BaseType::Int)),
        ("dividends.future_pay_date", Type::series(BaseType::Int)),
        // earnings.* namespace
        ("earnings", Type::unknown()),
        ("earnings.actual", Type::scalar(BaseType::String)),
        ("earnings.estimate", Type::scalar(BaseType::String)),
        ("earnings.standardized", Type::scalar(BaseType::String)),
        ("earnings.future_eps", Type::series(BaseType::Float)),
        (
            "earnings.future_period_end_time",
            Type::series(BaseType::Int),
        ),
        ("earnings.future_revenue", Type::series(BaseType::Float)),
        ("earnings.future_time", Type::series(BaseType::Int)),
        // splits.* namespace
        ("splits", Type::unknown()),
        ("splits.denominator", Type::scalar(BaseType::String)),
        ("splits.numerator", Type::scalar(BaseType::String)),
        // color.* constants
        ("color.aqua", Type::scalar(BaseType::Color)),
        ("color.black", Type::scalar(BaseType::Color)),
        ("color.blue", Type::scalar(BaseType::Color)),
        ("color.fuchsia", Type::scalar(BaseType::Color)),
        ("color.gray", Type::scalar(BaseType::Color)),
        ("color.green", Type::scalar(BaseType::Color)),
        ("color.lime", Type::scalar(BaseType::Color)),
        ("color.maroon", Type::scalar(BaseType::Color)),
        ("color.navy", Type::scalar(BaseType::Color)),
        ("color.olive", Type::scalar(BaseType::Color)),
        ("color.orange", Type::scalar(BaseType::Color)),
        ("color.purple", Type::scalar(BaseType::Color)),
        ("color.red", Type::scalar(BaseType::Color)),
        ("color.silver", Type::scalar(BaseType::Color)),
        ("color.teal", Type::scalar(BaseType::Color)),
        ("color.white", Type::scalar(BaseType::Color)),
        ("color.yellow", Type::scalar(BaseType::Color)),
        // plot.style_* constants
        ("plot", Type::unknown()),
        ("plot.style_area", Type::scalar(BaseType::Int)),
        ("plot.style_areabr", Type::scalar(BaseType::Int)),
        ("plot.style_circles", Type::scalar(BaseType::Int)),
        ("plot.style_columns", Type::scalar(BaseType::Int)),
        ("plot.style_cross", Type::scalar(BaseType::Int)),
        ("plot.style_histogram", Type::scalar(BaseType::Int)),
        ("plot.style_line", Type::scalar(BaseType::Int)),
        ("plot.style_linebr", Type::scalar(BaseType::Int)),
        ("plot.style_stepline", Type::scalar(BaseType::Int)),
        ("plot.style_stepline_diamond", Type::scalar(BaseType::Int)),
        ("plot.style_steplinebr", Type::scalar(BaseType::Int)),
        // plot.linestyle_* constants
        ("plot.linestyle_solid", Type::scalar(BaseType::Int)),
        ("plot.linestyle_dashed", Type::scalar(BaseType::Int)),
        ("plot.linestyle_dotted", Type::scalar(BaseType::Int)),
        // shape.* constants
        ("shape", Type::unknown()),
        ("shape.arrowdown", Type::scalar(BaseType::String)),
        ("shape.arrowup", Type::scalar(BaseType::String)),
        ("shape.circle", Type::scalar(BaseType::String)),
        ("shape.cross", Type::scalar(BaseType::String)),
        ("shape.diamond", Type::scalar(BaseType::String)),
        ("shape.flag", Type::scalar(BaseType::String)),
        ("shape.labeldown", Type::scalar(BaseType::String)),
        ("shape.labelup", Type::scalar(BaseType::String)),
        ("shape.square", Type::scalar(BaseType::String)),
        ("shape.triangledown", Type::scalar(BaseType::String)),
        ("shape.triangleup", Type::scalar(BaseType::String)),
        ("shape.xcross", Type::scalar(BaseType::String)),
        // location.* constants
        ("location", Type::unknown()),
        ("location.abovebar", Type::scalar(BaseType::String)),
        ("location.absolute", Type::scalar(BaseType::String)),
        ("location.belowbar", Type::scalar(BaseType::String)),
        ("location.bottom", Type::scalar(BaseType::String)),
        ("location.top", Type::scalar(BaseType::String)),
        // size.* constants
        ("size", Type::unknown()),
        ("size.auto", Type::scalar(BaseType::String)),
        ("size.huge", Type::scalar(BaseType::String)),
        ("size.large", Type::scalar(BaseType::String)),
        ("size.normal", Type::scalar(BaseType::String)),
        ("size.small", Type::scalar(BaseType::String)),
        ("size.tiny", Type::scalar(BaseType::String)),
        // hline.style_* constants
        ("hline", Type::unknown()),
        ("hline.style_dashed", Type::scalar(BaseType::Int)),
        ("hline.style_dotted", Type::scalar(BaseType::Int)),
        ("hline.style_solid", Type::scalar(BaseType::Int)),
        // label.style_* constants
        ("label.style_arrowdown", Type::scalar(BaseType::String)),
        ("label.style_arrowup", Type::scalar(BaseType::String)),
        ("label.style_circle", Type::scalar(BaseType::String)),
        ("label.style_cross", Type::scalar(BaseType::String)),
        ("label.style_diamond", Type::scalar(BaseType::String)),
        ("label.style_flag", Type::scalar(BaseType::String)),
        ("label.style_label_center", Type::scalar(BaseType::String)),
        ("label.style_label_down", Type::scalar(BaseType::String)),
        ("label.style_label_left", Type::scalar(BaseType::String)),
        (
            "label.style_label_lower_left",
            Type::scalar(BaseType::String),
        ),
        (
            "label.style_label_lower_right",
            Type::scalar(BaseType::String),
        ),
        ("label.style_label_right", Type::scalar(BaseType::String)),
        ("label.style_label_up", Type::scalar(BaseType::String)),
        (
            "label.style_label_upper_left",
            Type::scalar(BaseType::String),
        ),
        (
            "label.style_label_upper_right",
            Type::scalar(BaseType::String),
        ),
        ("label.style_none", Type::scalar(BaseType::String)),
        ("label.style_square", Type::scalar(BaseType::String)),
        ("label.style_triangledown", Type::scalar(BaseType::String)),
        ("label.style_triangleup", Type::scalar(BaseType::String)),
        ("label.style_xcross", Type::scalar(BaseType::String)),
        // line.style_* constants
        ("line.style_arrow_both", Type::scalar(BaseType::String)),
        ("line.style_arrow_left", Type::scalar(BaseType::String)),
        ("line.style_arrow_right", Type::scalar(BaseType::String)),
        ("line.style_dashed", Type::scalar(BaseType::String)),
        ("line.style_dotted", Type::scalar(BaseType::String)),
        ("line.style_solid", Type::scalar(BaseType::String)),
        // extend.* constants
        ("extend", Type::unknown()),
        ("extend.both", Type::scalar(BaseType::String)),
        ("extend.left", Type::scalar(BaseType::String)),
        ("extend.none", Type::scalar(BaseType::String)),
        ("extend.right", Type::scalar(BaseType::String)),
        // xloc.* constants
        ("xloc", Type::unknown()),
        ("xloc.bar_index", Type::scalar(BaseType::String)),
        ("xloc.bar_time", Type::scalar(BaseType::String)),
        // yloc.* constants
        ("yloc", Type::unknown()),
        ("yloc.abovebar", Type::scalar(BaseType::String)),
        ("yloc.belowbar", Type::scalar(BaseType::String)),
        ("yloc.price", Type::scalar(BaseType::String)),
        // text.align_* constants
        ("text", Type::unknown()),
        ("text.align_bottom", Type::scalar(BaseType::String)),
        ("text.align_center", Type::scalar(BaseType::String)),
        ("text.align_left", Type::scalar(BaseType::String)),
        ("text.align_right", Type::scalar(BaseType::String)),
        ("text.align_top", Type::scalar(BaseType::String)),
        // text.wrap_* constants
        ("text.wrap_auto", Type::scalar(BaseType::String)),
        ("text.wrap_none", Type::scalar(BaseType::String)),
        // text.format_* constants
        ("text.format_bold", Type::scalar(BaseType::String)),
        ("text.format_italic", Type::scalar(BaseType::String)),
        ("text.format_none", Type::scalar(BaseType::String)),
        // format.* constants
        ("format", Type::unknown()),
        ("format.inherit", Type::scalar(BaseType::String)),
        ("format.mintick", Type::scalar(BaseType::String)),
        ("format.percent", Type::scalar(BaseType::String)),
        ("format.price", Type::scalar(BaseType::String)),
        ("format.volume", Type::scalar(BaseType::String)),
        // order.* constants
        ("order", Type::unknown()),
        ("order.ascending", Type::scalar(BaseType::Int)),
        ("order.descending", Type::scalar(BaseType::Int)),
        // position.* constants
        ("position", Type::unknown()),
        ("position.bottom_center", Type::scalar(BaseType::String)),
        ("position.bottom_left", Type::scalar(BaseType::String)),
        ("position.bottom_right", Type::scalar(BaseType::String)),
        ("position.middle_center", Type::scalar(BaseType::String)),
        ("position.middle_left", Type::scalar(BaseType::String)),
        ("position.middle_right", Type::scalar(BaseType::String)),
        ("position.top_center", Type::scalar(BaseType::String)),
        ("position.top_left", Type::scalar(BaseType::String)),
        ("position.top_right", Type::scalar(BaseType::String)),
        // display.* constants
        ("display", Type::unknown()),
        ("display.all", Type::scalar(BaseType::Int)),
        ("display.data_window", Type::scalar(BaseType::Int)),
        ("display.none", Type::scalar(BaseType::Int)),
        ("display.pane", Type::scalar(BaseType::Int)),
        ("display.price_scale", Type::scalar(BaseType::Int)),
        ("display.status_line", Type::scalar(BaseType::Int)),
        // alert.* constants
        ("alert", Type::unknown()),
        ("alert.freq_all", Type::scalar(BaseType::String)),
        ("alert.freq_once_per_bar", Type::scalar(BaseType::String)),
        (
            "alert.freq_once_per_bar_close",
            Type::scalar(BaseType::String),
        ),
        // barmerge.* constants
        ("barmerge", Type::unknown()),
        ("barmerge.gaps_off", Type::scalar(BaseType::Int)),
        ("barmerge.gaps_on", Type::scalar(BaseType::Int)),
        ("barmerge.lookahead_off", Type::scalar(BaseType::Int)),
        ("barmerge.lookahead_on", Type::scalar(BaseType::Int)),
        // currency.* constants
        ("currency", Type::unknown()),
        ("currency.AUD", Type::scalar(BaseType::String)),
        ("currency.CAD", Type::scalar(BaseType::String)),
        ("currency.CHF", Type::scalar(BaseType::String)),
        ("currency.EUR", Type::scalar(BaseType::String)),
        ("currency.GBP", Type::scalar(BaseType::String)),
        ("currency.HKD", Type::scalar(BaseType::String)),
        ("currency.JPY", Type::scalar(BaseType::String)),
        ("currency.NOK", Type::scalar(BaseType::String)),
        ("currency.NONE", Type::scalar(BaseType::String)),
        ("currency.NZD", Type::scalar(BaseType::String)),
        ("currency.RUB", Type::scalar(BaseType::String)),
        ("currency.SEK", Type::scalar(BaseType::String)),
        ("currency.SGD", Type::scalar(BaseType::String)),
        ("currency.TRY", Type::scalar(BaseType::String)),
        ("currency.USD", Type::scalar(BaseType::String)),
        ("currency.ZAR", Type::scalar(BaseType::String)),
        ("currency.BTC", Type::scalar(BaseType::String)),
        ("currency.ETH", Type::scalar(BaseType::String)),
        ("currency.EGP", Type::scalar(BaseType::String)),
        ("currency.INR", Type::scalar(BaseType::String)),
        ("currency.KRW", Type::scalar(BaseType::String)),
        ("currency.MYR", Type::scalar(BaseType::String)),
        ("currency.PLR", Type::scalar(BaseType::String)),
        ("currency.USDT", Type::scalar(BaseType::String)),
        // dayofweek.* constants
        ("dayofweek.friday", Type::scalar(BaseType::Int)),
        ("dayofweek.monday", Type::scalar(BaseType::Int)),
        ("dayofweek.saturday", Type::scalar(BaseType::Int)),
        ("dayofweek.sunday", Type::scalar(BaseType::Int)),
        ("dayofweek.thursday", Type::scalar(BaseType::Int)),
        ("dayofweek.tuesday", Type::scalar(BaseType::Int)),
        ("dayofweek.wednesday", Type::scalar(BaseType::Int)),
        // scale.* constants
        ("scale", Type::unknown()),
        ("scale.left", Type::scalar(BaseType::Int)),
        ("scale.none", Type::scalar(BaseType::Int)),
        ("scale.right", Type::scalar(BaseType::Int)),
        // strategy.* constants
        ("strategy", Type::unknown()),
        ("strategy.cash", Type::scalar(BaseType::String)),
        (
            "strategy.commission.cash_per_contract",
            Type::scalar(BaseType::String),
        ),
        (
            "strategy.commission.cash_per_order",
            Type::scalar(BaseType::String),
        ),
        (
            "strategy.commission.percent",
            Type::scalar(BaseType::String),
        ),
        ("strategy.direction.all", Type::scalar(BaseType::String)),
        ("strategy.direction.long", Type::scalar(BaseType::String)),
        ("strategy.direction.short", Type::scalar(BaseType::String)),
        ("strategy.fixed", Type::scalar(BaseType::String)),
        ("strategy.oca.cancel", Type::scalar(BaseType::String)),
        ("strategy.oca.none", Type::scalar(BaseType::String)),
        ("strategy.oca.reduce", Type::scalar(BaseType::String)),
        ("strategy.percent_of_equity", Type::scalar(BaseType::String)),
        ("strategy.long", Type::scalar(BaseType::Int)),
        ("strategy.short", Type::scalar(BaseType::Int)),
        // math.* constants
        ("math.e", Type::scalar(BaseType::Float)),
        ("math.phi", Type::scalar(BaseType::Float)),
        ("math.pi", Type::scalar(BaseType::Float)),
        ("math.rphi", Type::scalar(BaseType::Float)),
        // font.* constants
        ("font", Type::unknown()),
        ("font.family_default", Type::scalar(BaseType::String)),
        ("font.family_monospace", Type::scalar(BaseType::String)),
        // adjustment.* constants
        ("adjustment", Type::unknown()),
        ("adjustment.dividends", Type::scalar(BaseType::String)),
        ("adjustment.none", Type::scalar(BaseType::String)),
        ("adjustment.splits", Type::scalar(BaseType::String)),
        ("backadjustment", Type::unknown()),
        ("backadjustment.inherit", Type::unknown()),
        ("backadjustment.off", Type::unknown()),
        ("backadjustment.on", Type::unknown()),
        ("settlement_as_close", Type::unknown()),
        ("settlement_as_close.inherit", Type::unknown()),
        ("settlement_as_close.off", Type::unknown()),
        ("settlement_as_close.on", Type::unknown()),
    ]
}
